### PR TITLE
added api cheat sheet

### PR DESCRIPTION
**Pull request by pertrai1**
Created an API cheat sheet for people to download for reference.

### CODE REVIEW

**Comment by riyadhalnur** [comment]
what's the reasoning behind serving the PDF from the `img` folder?

**Comment by pertrai1** [comment]
@riyadhalnur To be honest there was not one just the fact that I did not know where the best place to put it would be :-1:

**Comment by riyadhalnur** [comment]
@pertrai1 Haha. IMO a `static` folder would be nice.

@bower/contributors thoughts?

**Comment by prometheansacrifice** [comment]
Putting a PDF in `img` folder is misleading. +1 for `static` folder

**Comment by aishraj** [comment]
Perhaps using a static document serving location like a CDN or even an s3 bucket would be better ?

**Comment by sheerun** [comment]
Let's just link to it, instead embedding pdf: http://cheatography.com/pertrai1/cheat-sheets/bower-api/

**Pull request closed without merging**
