### PR TITLE
added npm install to brand masthead

### PR DESCRIPTION
**Pull request by pertrai1**
I did a fork on this one so it is close to the same as the other pull request plus the addition to the brand in the masthead

### CODE REVIEW

**Comment by pertrai1** [comment]
@benschwarz Sorry about that.

93e2e772-8d42-11e5-840d-365f30ee17f7

**Comment by desandro** [comment]
Thanks for taking a shot at this! I appreciate the intention here, but I cannot recommend merging this. `npm install bower` command is a bit technical, and might scare some people off who are not familiar with npm. Consider a lot of people find out about Bower and package management and they might have never heard of npm. I think it's in a better place where it currently is, as we first discuss what bower is, and how to install it, before we jump right into `npm install`.

**Comment by pertrai1** [comment]
@desandro - very good input that I did not take into consideration.

**Comment by navjotkaur1991** [comment]
Hey

M new to bower. Can anyone please help me out with what needs to be done.
Please consider that I would only be able to work on weekends.

**Comment by sheerun** [comment]
Also, I'm more and more convinced that installing bower globally is a bad idea..

It's better to use it as npm dependency in project.

**Comment by desandro** [comment]
> I'm more and more convinced that installing bower globally is a bad idea.

Depends on a technical level. I've never run into trouble with global Bower, but my use cases are more installing and publishing packages.

**Pull request closed without merging**
