### PR TITLE
Blog post about voluteering with Bower

### PR DESCRIPTION
**Pull request by pertrai1**

### CODE REVIEW

**Comment by desandro** [comment]
Great post! We just released 1.7.0 yesterday so I'd like to wait another day, then post it.

**Comment by sheerun** [comment]
Or even longer ;) We don't want to spam posts, and then be silent for weeks

**Comment by pertrai1** [comment]
Not a problem.

**Comment by contolini** [comment]
I love this post so much. :smile: 

Minor typo in the filename: *voluteering* should be *volunteering*

**Comment by pertrai1** [comment]
@contolini thank you and good catch on typo

**Comment by benschwarz** [comment]
@pertrai1 👏 Great job — That's a great thanks to the peeps who helped you too! Fantastic :+1:

**Comment by pertrai1** [comment]
@sheerun I can make sure that the blog does not go silent for weeks and is not posts that are posted just to fill in the blanks.

**Comment by pertrai1** [comment]
@sheerun @desandro Any chance we can put this up now?

**Comment by sheerun** [comment]
Yes, I think we can publish it :)

**Comment by sheerun** [comment]
@desandro Could review it linguistically and push merge button?

**Comment by desandro** [comment]
merrrrrged and [tweeted](https://twitter.com/bower/status/677566332922142720) :bird:

**Pull request merged**
