### PR TITLE
change list to table of contents

### PR DESCRIPTION
**Pull request by pertrai1**
To save real estate, changed the list of commands to a table

### CODE REVIEW

**Comment by desandro** [comment]
Not a bad idea, but lists has better accessibility and is easier to scan.

**Comment by oosidat** [comment]
Also, lists are easier to access while reading docs on mobile. Markdown tables aren't very mobile (or small-screen)-friendly.

**Comment by sheerun** [comment]
yup

**Comment by pertrai1** [comment]
@desandro @oosidat  - Great feedback guys. thanks for taking the time

**Pull request closed without merging**
