### PR TITLE
Site Improvements

### PR DESCRIPTION
**Pull request by raphamorim**
Some changes i have added into the project:

-  Reduced excessive margins in h2, h3 ( 520392f988fb88b85add4a6c07df5f21df4ec286 )
-  Make twitter script run asynchronously ( 24e616df1626f64d688675ed470b9930a36bda97 )
   - References: [Google Developers](https://developers.google.com/speed/docs/insights/UseAsync), [w3schools](http://www.w3schools.com/tags/att_script_async.asp)
-  Added social media tags, used by open graph protocol ( d8393acd162b208ccbb0c6f1028ecdb3923c3ca8 )
   -  Reference: [OGP](http://ogp.me/)
-  Added viewport tag and use media queries to apply flexibility to site ( d8393acd162b208ccbb0c6f1028ecdb3923c3ca8 , ab57a8f9d4a9405013c2352c89576c01918faca2 , d60c23d3245ac85135c6bbbb530cb13f7eea66be )

**Some screenshots about the last change:**

Samsung Galaxy Note ||:
captura de tela 2014-07-23 as 23 29 42

HTC one X:
captura de tela 2014-07-23 as 23 31 34

Samsung Galaxy S4:
captura de tela 2014-07-23 as 22 13 20

Google Nexus 4:
captura de tela 2014-07-23 as 22 13 57

### CODE REVIEW

**Comment by sheerun** [comment]
@paulohp will review it for you @desandro, ok?

**Comment by paulohp** [comment]
I was looking here and looks pretty solid :+1: 

Who can merge this @sheerun ?

**Comment by sheerun** [comment]
@paulohp Feel free to resolve conflicts and merge :)

**Comment by desandro** [comment]
:+1:

**Pull request merged**
