### PR TITLE
add documentation for bower/config PR-32

### PR DESCRIPTION
**Pull request by pwang2**
see https://github.com/bower/config/pull/32.

This need to be merged only if https://github.com/bower/config/pull/32 is merged. 

Thanks.

### CODE REVIEW

**Comment by paulohp** [comment]
Thanks @pwang2 for the update :)

**Comment by sheerun** [comment]
We need to wait until this feature is shipped in bower

**Comment by dvidsilva** [comment]
Looks like https://github.com/bower/config/pull/32 was merged, should we merge this too?

**Comment by sheerun** [comment]
yes, but the syntax is slightly different, you don't need to use quotes

**Comment by paulohp** [comment]
@sheerun what we need to change to merge this ?

**Comment by sheerun** [comment]
@paulohp the array syntax is different than documented, there are no quotes

**Comment by paulohp** [comment]
screen shot 2016-03-16 at 6 32 28 am
?

**Comment by sheerun** [comment]
yes

**Pull request merged**
