### PR TITLE
Second blog post

### PR DESCRIPTION
**Pull request by contolini**
Here's a quick follow-up post to coincide with the 1.7.0 release that's going live today/tomorrow.

@bower/contributors Feedback welcome.

### CODE REVIEW

**Comment by pertrai1** [comment]
:+1: Great write up

**Comment by riyadhalnur** [comment]
:+1:

**Comment by heinst** [comment]
:thumbsup:

**Comment by zzarcon** [comment]
Great work :+1:

**Comment by riyadhalnur** [comment]
i think we have enough to go forward and merge this. will wait till the release is done and go ahead and merge this.

**Comment by sheerun** [comment]
@desandro Could you review?

**Comment by desandro** [comment]
Love it! Thanks so much for writing this up. Minor details

+ Mind changing the `http://bower.io/blog/...` URL to domain-relative `/blog/...`
+ should we point people to Gitter or Dischord?

This is a great example of how _anyone_ can contribute to the Bower blog. Anyone can submit a PR and we'll review

**Comment by contolini** [comment]
Cool, I fixed the links and rebased. The badge in the main readme points to gitter. I'll fix that now.

**Comment by KatieLo** [comment]
:+1:

**Comment by sheerun** [comment]
Bower 1.7.0 is now public :)

**Comment by BenMann** [comment]
🎉🎊

**Pull request merged**
