### PR TITLE
Change in the header navigation layout

### PR DESCRIPTION
**Pull request by pertrai1**
Giving the header navigation a different look to separate it from the masthead and re-position logo

### CODE REVIEW

**Comment by faceleg** [comment]
Could you add a screenshot for us to look at please?

**Comment by pertrai1** [comment]
Screenshot uploaded a little weird. If you need better let me know.

bower-screenshot

**Comment by faceleg** [comment]
@desandro please review

**Comment by desandro** [comment]
Hi! Thanks for giving this a shot. Navigation across Bower domains is worth refactoring, but I don't feel this is much of an improvement. Red on yellow feels a bit McDonalds. I've never been a fixed navigation. It's like a reminder that I should always be somewhere else rather than the page I'm on.

**Comment by pertrai1** [comment]
@desandro Sounds good. I did not know about the color as I have been using the logo as the color pallete. Moving from fixed to static position is not a problem. I will kill the PR and wait until there are any requests from the website team for help.

**Pull request closed without merging**
