### PR TITLE
Add blog; first post "Bower is alive, looking for contributors"

### PR DESCRIPTION
**Pull request by desandro**
screen shot 2015-11-18 at 4 07 41 pm

Also added first blog post, looking for contributors. You can review: https://gist.github.com/desandro/564a630be03cf295e6cc

I'd like to merge in 24 hours.

### CODE REVIEW

**Comment by kodypeterson** [comment]
Looks good to me. This is a great step for Bower and something that was on my list to bring up. Great work!

**Comment by faceleg** [comment]
It's **very** difficult for me not to jam on that "merge" button right now... @sheerun?

**Comment by paulohp** [comment]
Looks Awesome! Great job @desandro !

**Comment by sheerun** [comment]
Thank you! It is rather difficult to me to write such good prose :)

**Pull request merged**
