### PR TITLE
Clean CSS & reworked mobile menu

### PR DESCRIPTION
**Pull request by BenMann**
1) Cleaning up CSS (remove medias.css)
2) Reworked mobile menu —> „Menu button“ and keep the list over blocks
that were in place before

cc: @desandro — as discussed in https://github.com/bower/bower.github.io/issues/189. This keeps the main-nav on top and the actual docs-nav as is but hidden behind a button, so it doesn't push the content down too much. Uses a bit of JS to expand/collapse.

collapsed
extended

### CODE REVIEW

**Comment by sheerun** [comment]
Looks awesome :)

**Comment by paulohp** [comment]
I really like it! Thanks @BenMann for your hard work here. :+1:

**Comment by desandro** [comment]
Excellent work! This is sooooo much better. Merged. I did change the header treatment on sub pages to be one line. 

screen shot 2015-12-06 at 10 24 59 am

**Comment by BenMann** [comment]
Thanks :)
Would have done the same on stats and search I think (one line).
Will get there soon and unify the header.

**Pull request merged**
