### PR TITLE
Add new post

### PR DESCRIPTION
**Pull request by BenMann**
Just talking about recent updates and their implications. None of them
were documented elsewhere I guess. All eyes on this welcome!

### CODE REVIEW

**Comment by desandro** [comment]
Thanks for writing this up!

+ Change filename to `2016-04-10-update-on-recent-changes.md`.
+ Can you add update instructions so people know how to get these updates? "Update to latest version of bower `npm install -g bower`

**Comment by BenMann** [comment]
Sure thing. Fixed what you found!
I went by the chaneglog but there might be more interesting stuff to talk about.
Also not native english, so an eye on that would be great... :sweat_smile:

**Comment by prometheansacrifice** [comment]
:+1:

**Comment by desandro** [comment]
Looks good. :shipit:

**Comment by sheerun** [comment]
Last release is actually 1.7.7.

**Comment by BenMann** [comment]
Added 1.7.7 — @sheerun the big green button is all yours I guess? :)

**Comment by sheerun** [comment]
sure :)

**Pull request merged**
