### PR TITLE
Remove yellow masthead background

### PR DESCRIPTION
**Pull request by pertrai1**
Looks cleaner with a white background with the rest of the page

### CODE REVIEW

**Comment by pertrai1** [comment]
@sheerun Only reason I assigned you was to get you to take a look at the proposed small change. Do not know yet at this point who else to try to get to look at proposed PR's.

**Comment by benschwarz** [comment]
Can you screenshot it please @pertrai1 
@desandro would be a good sign off on this one

**Comment by desandro** [comment]
Yellow is the brand. Yellow is what makes it special. bower.io has been yellow for years. I recommend keeping the yellow.

`npm install bower` command is a bit technical, and might scare some people off who are not familiar with npm. Consider a lot of people find out about Bower and package management and they might have never heard of npm. I think it's in a better place where it currently is, as we first discuss what bower is, and how to install it, before we jump right into `npm install`.

**Comment by pertrai1** [comment]
@desandro Sounds good to me.

**Pull request closed without merging**
